-- drop_tables.sql
-- Fecha: 01-01-2024
-- Autor: barrikeit
-- Versión: 0.0.1

DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS friendships CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS ranks CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS users_roles CASCADE;
DROP TABLE IF EXISTS games CASCADE;
DROP TABLE IF EXISTS games_users_colors CASCADE;
DROP TABLE IF EXISTS game_states CASCADE;
DROP TABLE IF EXISTS colors CASCADE;
DROP TABLE IF EXISTS events CASCADE;
