spring:
  flyway:
    table: flyway_schema_history
    baseline-on-migrate: true
    validate-on-migrate: true
    validate-migration-naming: true
    ignore-migration-patterns: '*:missing'
    locations: classpath:db
    enabled: true
