server:
  servlet:
    encoding:
      force-response: true

spring:
  boot:
    admin:
      monitor:
        default-timeout: 60000
        status-interval: 15000
        status-lifetime: 15000
  jackson.serialization:
    FAIL_ON_EMPTY_BEANS: false
  jpa:
    generate-ddl: false
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  jmx:
    enabled: false
  zipkin:
    enabled: false
  web:
    locale: es_ES
