security:
  cors:
    allowed:
      methods: GET,HEAD,POST,PUT,DELETE
      headers: "Authorization,content-type,x-aei-called-service"
      origins: http://localhost:9891, http://localhost:4200
    enabled: true
    path:
      pattern: /**
  jwt:
    issuer: keit
    secret: keit_secret
    expiration: 3600
    expiration-refresh: 4500
  app-validator-filter:
    app-self-name: 'generic-security'
    app-header-name: 'x-aei-called-service'
    app-header-name-validation-Filter: true
    app-security-name: 'generic-security-service'